import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Terminal, Code2, Database, Brain, ArrowRight, Copy, Check, Play } from "lucide-react";
import { soundFX } from "../lib/soundFX";

const PLAYGROUND_TOOLS = [
  {
    id: "sql",
    name: "AI SQL Generator",
    icon: Database,
    badge: "NL to SQL",
    placeholder: "e.g. Find all students who scored above 85% in Math and order by date",
    sampleQuery: "Get top 5 customers with highest total spending in 2026 and their latest order date",
    mockEngine: (input) => {
      const q = input.toLowerCase();
      if (q.includes("customer") || q.includes("spending")) {
        return `-- Generated by Abdikadir AI Agent (PostgreSQL / Supabase)
SELECT 
    c.id AS customer_id,
    c.full_name,
    COUNT(o.id) AS total_orders,
    COALESCE(SUM(o.total_amount), 0) AS total_spent,
    MAX(o.created_at) AS latest_order_date
FROM customers c
INNER JOIN orders o ON o.customer_id = c.id
WHERE EXTRACT(YEAR FROM o.created_at) = 2026
GROUP BY c.id, c.full_name
ORDER BY total_spent DESC
LIMIT 5;`;
      }
      if (q.includes("student") || q.includes("school") || q.includes("grade")) {
        return `-- Generated by Abdikadir AI Agent (School Management Schema)
SELECT 
    s.id,
    s.first_name || ' ' || s.last_name AS student_name,
    c.course_name,
    g.score,
    g.recorded_at
FROM students s
JOIN enrollments e ON e.student_id = s.id
JOIN grades g ON g.enrollment_id = e.id
JOIN courses c ON c.id = e.course_id
WHERE LOWER(c.course_name) LIKE '%math%' AND g.score > 85
ORDER BY g.recorded_at DESC;`;
      }
      return `-- Generated SQL for: "${input}"
SELECT 
    id, 
    title, 
    status, 
    created_at 
FROM records 
WHERE status = 'active' 
ORDER BY created_at DESC 
LIMIT 10;`;
    }
  },
  {
    id: "code",
    name: "AI Code Explainer & Optimizer",
    icon: Code2,
    badge: "Refactor",
    placeholder: "Paste any C#, JavaScript, or Python function to analyze and optimize...",
    sampleQuery: `async function fetchUserData(ids) {
  let results = [];
  for (let id of ids) {
    let res = await fetch('/api/user/' + id);
    results.push(await res.json());
  }
  return results;
}`,
    mockEngine: () => {
      return `/* ⚡ Abdikadir AI Optimization Report */
// 🔴 Issue Found: Sequential 'for...await' network bottleneck (O(N) waterfall).
// 🟢 Optimized Solution: Parallel Promise.all execution with batch safety.

async function fetchUserDataOptimized(ids) {
  if (!Array.isArray(ids) || ids.length === 0) return [];
  
  // Parallel batch fetching (10x faster network throughput)
  const userPromises = ids.map(async (id) => {
    try {
      const response = await fetch(\`/api/user/\${encodeURIComponent(id)}\`);
      if (!response.ok) throw new Error(\`HTTP \${response.status}\`);
      return await response.json();
    } catch (err) {
      console.warn(\`Failed fetching user \${id}:\`, err.message);
      return null;
    }
  });

  const results = await Promise.allSettled(userPromises);
  return results
    .filter(r => r.status === 'fulfilled' && r.value !== null)
    .map(r => r.value);
}`;
    }
  },
  {
    id: "architecture",
    name: "AI Architecture Advisor",
    icon: Brain,
    badge: "Systems",
    placeholder: "Describe a software feature or system to get architecture recommendations...",
    sampleQuery: "How to build a real-time face recognition attendance system for 500+ employees?",
    mockEngine: () => {
      return `🧠 System Architecture Blueprint:
1. Hardware / Edge:
   - IP CCTV Cameras streaming RTSP via H.264
   - Edge Gateway (Raspberry Pi 5 / Jetson Nano) running OpenCV Haar/RetinaFace

2. AI Pipeline:
   - Face Detection: InsightFace / FaceNet 512-dim feature embedding
   - Matching: pgvector in PostgreSQL (cosine distance threshold < 0.35)

3. Backend Service:
   - FastAPI (Python) for asynchronous batch inference
   - C# .NET Management Dashboard for HR live telemetry
   - Supabase Webhooks for instant Telegram alerts on unauthorized entries`;
    }
  }
];

export default function AIPlaygroundHub() {
  const [activeTab, setActiveTab] = useState(PLAYGROUND_TOOLS[0].id);
  const [inputVal, setInputVal] = useState(PLAYGROUND_TOOLS[0].sampleQuery);
  const [outputVal, setOutputVal] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [copied, setCopied] = useState(false);

  const activeTool = PLAYGROUND_TOOLS.find(t => t.id === activeTab) || PLAYGROUND_TOOLS[0];

  const handleTabChange = (tool) => {
    soundFX.playClick();
    setActiveTab(tool.id);
    setInputVal(tool.sampleQuery);
    setOutputVal("");
  };

  const handleRun = () => {
    if (!inputVal.trim()) return;
    soundFX.playPop();
    setIsProcessing(true);
    setOutputVal("");

    setTimeout(() => {
      const res = activeTool.mockEngine(inputVal);
      setOutputVal(res);
      setIsProcessing(false);
      soundFX.playSuccess();
    }, 600);
  };

  const handleCopy = () => {
    if (!outputVal) return;
    navigator.clipboard.writeText(outputVal);
    setCopied(true);
    soundFX.playClick();
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section className="relative w-full py-16 px-4 md:px-10 bg-[#08080C] overflow-hidden border-t border-b border-white/[0.05]">
      {/* Background glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[350px] bg-[#4FFFB0]/[0.03] rounded-full blur-[120px] pointer-events-none" />

      <div className="relative max-w-5xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#4FFFB0]/10 border border-[#4FFFB0]/20 text-[#4FFFB0] text-xs font-mono mb-3">
            <Sparkles size={13} />
            <span>Interactive Proof of Work</span>
          </div>
          <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight">
            AI Engineering <span className="text-[#4FFFB0]">Live Playground</span>
          </h2>
          <p className="text-white/40 text-sm max-w-xl mx-auto mt-2 font-mono">
            Test custom AI utilities designed by Abdikadir. Generate SQL, refactor code, or plan system architectures in real time.
          </p>
        </div>

        {/* Tool Navigation Tabs */}
        <div className="flex flex-wrap items-center justify-center gap-2 mb-6">
          {PLAYGROUND_TOOLS.map((tool) => {
            const Icon = tool.icon;
            const isActive = activeTab === tool.id;
            return (
              <button
                key={tool.id}
                onClick={() => handleTabChange(tool)}
                className={`flex items-center gap-2 px-4 py-2.5 rounded-xl border text-xs font-mono transition-all duration-200 cursor-pointer ${
                  isActive
                    ? "bg-[#4FFFB0]/15 border-[#4FFFB0] text-[#4FFFB0] shadow-[0_0_20px_rgba(79,255,176,0.15)]"
                    : "bg-white/[0.02] border-white/10 text-white/60 hover:text-white hover:border-white/20"
                }`}
              >
                <Icon size={14} className={isActive ? "text-[#4FFFB0]" : "text-white/40"} />
                <span className="font-semibold">{tool.name}</span>
                <span className="text-[10px] px-1.5 py-0.5 rounded bg-white/10 text-white/50">{tool.badge}</span>
              </button>
            );
          })}
        </div>

        {/* Interactive Console Workspace */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 rounded-2xl border border-white/10 bg-[#0d0d14]/90 backdrop-blur-xl p-4 md:p-6 shadow-2xl">
          {/* Left: Input Box */}
          <div className="flex flex-col justify-between border-b md:border-b-0 md:border-r border-white/10 pb-4 md:pb-0 md:pr-4">
            <div>
              <div className="flex items-center justify-between mb-3 text-xs font-mono text-white/50">
                <span className="flex items-center gap-1.5">
                  <Terminal size={13} className="text-[#4FFFB0]" />
                  PROMPT_INPUT
                </span>
                <button
                  onClick={() => setInputVal(activeTool.sampleQuery)}
                  className="text-[11px] text-[#4FFFB0]/70 hover:text-[#4FFFB0] transition-colors underline cursor-pointer"
                >
                  Load Sample
                </button>
              </div>
              <textarea
                value={inputVal}
                onChange={(e) => setInputVal(e.target.value)}
                placeholder={activeTool.placeholder}
                rows={8}
                className="w-full bg-black/40 border border-white/10 rounded-xl p-3.5 text-xs text-white font-mono placeholder:text-white/20 focus:outline-none focus:border-[#4FFFB0]/40 transition-colors resize-none"
              />
            </div>

            <div className="mt-4 flex items-center justify-between">
              <span className="text-[11px] font-mono text-white/30">Engine: Abdikadir-LLM-v2.4</span>
              <motion.button
                onClick={handleRun}
                disabled={isProcessing || !inputVal.trim()}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#4FFFB0] hover:bg-[#4FFFB0]/90 text-black font-mono font-bold text-xs shadow-[0_0_20px_rgba(79,255,176,0.25)] transition-all cursor-pointer disabled:opacity-50"
              >
                {isProcessing ? (
                  <>
                    <span className="w-3.5 h-3.5 border-2 border-black/30 border-t-black rounded-full animate-spin" />
                    <span>Processing...</span>
                  </>
                ) : (
                  <>
                    <Play size={13} fill="currentColor" />
                    <span>Execute AI</span>
                  </>
                )}
              </motion.button>
            </div>
          </div>

          {/* Right: Output Console */}
          <div className="flex flex-col justify-between pt-4 md:pt-0 md:pl-4">
            <div>
              <div className="flex items-center justify-between mb-3 text-xs font-mono text-white/50">
                <span className="flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-[#4FFFB0] animate-pulse" />
                  AI_GENERATED_OUTPUT
                </span>
                {outputVal && (
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-1 text-[11px] text-white/60 hover:text-white transition-colors cursor-pointer"
                  >
                    {copied ? <Check size={12} className="text-[#4FFFB0]" /> : <Copy size={12} />}
                    <span>{copied ? "Copied" : "Copy"}</span>
                  </button>
                )}
              </div>

              <div className="w-full h-52 bg-black/60 border border-white/10 rounded-xl p-3.5 text-xs text-[#4FFFB0] font-mono overflow-auto whitespace-pre-wrap leading-relaxed">
                {isProcessing ? (
                  <div className="flex items-center justify-center h-full text-white/30 gap-2">
                    <span className="w-2 h-2 rounded-full bg-[#4FFFB0] animate-ping" />
                    <span>Synthesizing intelligent output...</span>
                  </div>
                ) : outputVal ? (
                  outputVal
                ) : (
                  <span className="text-white/20 italic">
                    Press "Execute AI" to generate real-time output...
                  </span>
                )}
              </div>
            </div>

            <div className="mt-4 flex items-center justify-between text-[11px] font-mono text-white/40">
              <span>Status: Ready</span>
              <span className="text-[#4FFFB0]/80">Zero Latency Local Engine</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
